### ISSUE TITLE
how can I use your code with my data?

### ISSUE THREAD

**Issue by mrmrn** [lujunzju/Machine-for-Air-Ticket-Predicting-Ongoing-#2]
hello,
thank you for the good paper and this open source repo.
I have 3 weeks snapshot of an airline flights. the snapshot have a 1 hour time interval with before and next snapshot and contains time of snapshot, date&time of flight, flight number and some additional unnecessary data(or maybe I think they are unnecessary!!).
So my question is: can I use this code to predict the price of tese tickets? and how to use this code if I can use it.

**Comment by junlulocky** [comment]
Hey, thanks for your question. See the python file Classification/ClassificationBase.py, the data should be something has the following features which are commented in the file. And also similar for regression problems:

        # normalize feature 10, feature 11, feature 13
        # feature 0~7: flight number dummy variables
        # feature 8: departure date; feature 9: observed date state;
        # feature 10: minimum price; feature 11: maximum price
        # fearure 12: prediction(buy or wait); feature 13: price

**Comment by mrmrn** [comment]
so, what is the minimum and maximum price?

**Comment by junlulocky** [comment]
it is the minimum and maximum price during the previous history record

**Comment by mrmrn** [comment]
so I have not them.
I am crawling some price, take a snapshot from prices, and after 1 hour I take another snap shot.
I think our problem is a bit different.
I want to predict the price of a ticket at least 2 weeks before departure date and I will be happy where the minimum price occurs in this 2 weeks

**Comment by junlulocky** [comment]
Yes, you do not have them directly. Basically, you need to calculate by some codes. I think basically we are dealing the same problem. But you need to calculate the historical minimum and maximum price because you got the historical price already. So it is pretty simple.

**Comment by mrmrn** [comment]
yeah,
but do you evaluate this Hidden Markov model sequence classification based adaptive boost decision tree classification  with xgboost? I think xgboost may be better(I dont know why!!?)

**Comment by junlulocky** [comment]
Yes, you definitely could. But the main idea of this paper is to model the air ticket predicting problem with machine learning models. :)

**Comment by mrmrn** [comment]
and xgboost is a machine learning model,too

**Comment by junlulocky** [comment]
yes, I understand. What I mean is the MODELING stuff. And there are also many other machine learning models. I cannot use all of them to fit on only one paper.

**Comment by mrmrn** [comment]
yeah,
I mean do you evaluate your proposed model outputs with xgboost outputs?
ok I will try your code If I could run it :D and will report the output of other models such as xgboost on my dataset.
thank you

**Comment by junlulocky** [comment]
Good, thanks!
